database:
  host: mysql.db.svc.cluster.local
  name: tenant_1
  password: ziXAEILg5gXD4jEI
  user: tenant_1_user
plugins: '["woocommerce-core"]'
preferences: '{"language": "en"}'
resources:
  limits:
    cpu: '1'
    memory: 2Gi
  requests:
    storage: 20Gi
tenant:
  domain: shop1.genoras.com
  location: EMEA
  name: tenant-01
