apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wp
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wp
    spec:
      containers:
      - name: wordpress
        image: wordpress:php8.1-apache
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ .Release.Name }}-mysql
        - name: WORDPRESS_DB_NAME
          value: {{ .Release.Name | replace "-" "_" }}_db
        - name: WORDPRESS_DB_USER
          value: {{ .Release.Name | replace "-" "_" }}_user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: mysql-password
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wp-storage
          mountPath: /var/www/html
      volumes:
      - name: wp-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-wp-pvc
